# Generated by Django 5.2.7 on 2025-10-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rating_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
